services:
  # Application Service (PHP-FPM)
  app:
    build:
      args:
        user: sail
        uid: 1000 # Replace with your local user ID if necessary
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini # Optional: custom php.ini settings
    networks:
      - app-network
    # depends_on:
      # - db # If you have a database service
      # - redis # If you use Redis

  # Web Server Service (Nginx)
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "5173:5173" # For Vite, if you're using it
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # Database Service (MySQL example)
  # db:
  #   image: mysql:8.0
  #   container_name: laravel_db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE:-laravel}
  #     MYSQL_USER: ${DB_USERNAME:-sail}
  #     MYSQL_PASSWORD: ${DB_PASSWORD:-password}
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #     # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf # Optional: custom mysql config
  #   networks:
  #     - app-network
  #   healthcheck:
  #       test: ["CMD", "mysqladmin", "ping", "-p$${DB_PASSWORD:-password}"]
  #       retries: 3
  #       timeout: 5s

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local 